version: 2.0

workflows:
  version: 2
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: clojure/lein
    steps:
      - checkout
      - run:
          name: testttttsssss
          command: lein test
